[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
#futures = { version = "0.3.30", feature = ["full"] }
rand = "0.8.5"

tokio = { version = "1.40", features = ["full", "time"] }
